// Generated by scripts/fetch-games.mjs from the Roblox API. Do not edit by hand:
// set name, description or thumbnail on the game in content.js to override a value.
window.GAME_DATA = {
  "6403373529": {
    "name": "Slap Battles",
    "description": "A game about slapping people into oblivion using different gloves with unique abilities.",
    "creator": "Slap Battles",
    "visits": 3644084750,
    "favorites": 4650913,
    "thumbnail": "assets/games/6403373529.webp"
  },
  "18799085098": {
    "name": "Hide or OOF!",
    "description": "Hide or OOF is a combination of hide and seek and prop hunt! The game was previously called Hide or Die.",
    "creator": "0 CCU Games",
    "visits": 802875864,
    "favorites": 9671076,
    "thumbnail": "assets/games/18799085098.webp"
  },
  "13278651209": {
    "name": "Pet Store Tycoon 2",
    "description": "Build your dream pet store, adopt and raise pets, combine pets to make them more valuable, manage your own employees, and roleplay with friends!",
    "creator": "Splitbrick Studio",
    "visits": 8097084,
    "favorites": 36749,
    "thumbnail": "assets/games/13278651209.webp"
  },
  "12981384028": {
    "name": "Sword Swing Simulator",
    "description": "Kill dummies with swords! Explore new zones! Collect wins to buy new stuff! Open eggs to get rare pets! Buy new swords to do more damage! Fight for wins in our PvP Zone!",
    "creator": "Sword Swing Simulator",
    "visits": 11323971,
    "favorites": 393699,
    "thumbnail": "assets/games/12981384028.webp"
  }
};
