// Fetches details for every Roblox game linked in content.js and writes games-data.js.
// Runs in GitHub Actions (see .github/workflows/update-games.yml) because Roblox's APIs
// don't allow browsers on other sites to read them. Run locally with: node scripts/fetch-games.mjs
import { readFile, writeFile, mkdir } from "node:fs/promises";
import vm from "node:vm";

const root = new URL("../", import.meta.url);

// content.js assigns window.SITE, so run it with a stand-in window object.
const context = { window: {} };
vm.runInNewContext(await readFile(new URL("content.js", root), "utf8"), context);
const games = context.window.SITE.games || [];

async function getJSON(url) {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${res.status} ${url}`);
  return res.json();
}

// "[UPDATE🧤] Slap Battles👏" -> "Slap Battles"
function cleanName(name) {
  return name
    .replace(/\[[^\]]*\]|\([^)]*\)/g, "")
    .replace(/[\p{Extended_Pictographic}\u{FE0F}\u{200D}\u{20E3}]/gu, "")
    .replace(/\s+/g, " ")
    .trim();
}

// First substantial paragraph, emoji removed, cut to whole sentences within ~220 characters.
function cleanDescription(text) {
  const paragraphs = text
    .split(/\n\s*\n/)
    .map((p) => p
      .replace(/[\p{Extended_Pictographic}\u{FE0F}\u{200D}\u{20E3}]/gu, "")
      .split("\n").map((line) => line.trim()).filter(Boolean).join(" ")
      .replace(/\s+/g, " ")
      .trim())
    .filter((p) => p.length >= 60 && p !== p.toUpperCase());
  const para = paragraphs[0] || "";
  const sentences = para.match(/[^.!?]+[.!?]+(\s|$)|[^.!?]+$/g) || [para];
  let out = "";
  for (const s of sentences) {
    if (out && (out + s).length > 220) break;
    out += s;
  }
  out = out.trim();
  return out.length > 260 ? out.slice(0, 257).replace(/\s+\S*$/, "") + "…" : out;
}

const places = games
  .map((g) => (g.link || "").match(/roblox\.com\/games\/(\d+)/))
  .filter(Boolean)
  .map((m) => m[1]);

const data = {};
await mkdir(new URL("assets/games/", root), { recursive: true });

for (const placeId of places) {
  const { universeId } = await getJSON(`https://apis.roblox.com/universes/v1/places/${placeId}/universe`);
  const [info] = (await getJSON(`https://games.roblox.com/v1/games?universeIds=${universeId}`)).data;
  const thumbs = await getJSON(
    `https://thumbnails.roblox.com/v1/games/multiget/thumbnails?universeIds=${universeId}&countPerUniverse=1&defaults=true&size=768x432&format=Webp`
  );
  const imageUrl = thumbs.data?.[0]?.thumbnails?.[0]?.imageUrl;

  // Save the thumbnail locally: Roblox CDN links expire, a file in the repo doesn't.
  let thumbnail = "";
  if (imageUrl) {
    const img = await fetch(imageUrl);
    if (img.ok) {
      thumbnail = `assets/games/${placeId}.webp`;
      await writeFile(new URL(thumbnail, root), Buffer.from(await img.arrayBuffer()));
    }
  }

  data[placeId] = {
    name: cleanName(info.name),
    description: cleanDescription(info.description || ""),
    creator: info.creator?.name || "",
    visits: info.visits,
    favorites: info.favoritedCount,
    thumbnail
  };
  console.log(`${placeId}: ${data[placeId].name} (${info.visits.toLocaleString("en-US")} visits)`);
}

const out =
  "// Generated by scripts/fetch-games.mjs from the Roblox API. Do not edit by hand:\n" +
  "// set name, description or thumbnail on the game in content.js to override a value.\n" +
  "window.GAME_DATA = " + JSON.stringify(data, null, 2) + ";\n";
await writeFile(new URL("games-data.js", root), out);
